### ISSUE TITLE
wrong naming of wait-on-error

### ISSUE THREAD

**Issue by simonostendorf** [JonasProgrammer/docker-machine-driver-hetzner#100]
Since version 3.11.0 (release of --wait-on-error) i cant use the driver within rancher.

The problem:
Rancher thinks all parameters start with the provider name (--hetzner-image, --hetzner-ssh-key etc.), but --wait-on-error doesnt. 
Rancher than shows "onError" als parameter, but if you create the cluster later, rancher puts -hetzner in front, so --hetzner-on-error could not be found.

Solution:
Rename parameter --wait-on-error to --hetzner-wait-on-error to keep naming conventions.

**Comment by JonasProgrammer** [comment]
Hi,

sorry for the inconvenience. Indeed, I did not think too much about the flag name and just went with it when adding to the README after merging #98. I certainly did notice it then, but I honestly did not think this would cause problems downstream.

Summoning @mookie-, could you please check if your requirements would still be satisfied when renaming the flag 'appropriately', i.e. `--hetzner-wait-on-error`? If so, I'd like to publish a patch release renaming the flag asap. While it is techincally a breaking change, I don't think many people are currently relying on that very flag.

**Comment by mookie-** [comment]
I don't think anyone do rely on this flag. If so they hopefully read the commits/release notes.
Sorry @simonostendorf for breaking your setup.
FYI: The waiting period already improved our setup as we don't use up all our API Requests when hetzner didn't create the servers we needed. So thank you very much @JonasProgrammer for your fast response and adding features.

**Comment by simonostendorf** [comment]
This didn't break my setup. I am testing things in my dev env before using them in prod. So no problem, just want to report this issue :)

**Comment by JonasProgrammer** [comment]
Thanks for fixing this @mookie-. I originally meant to do it myself and just have your input on whether that breaks something for you, but getting the fix provided without any involvement obviously puts the cherry atop.
