### ISSUE TITLE
image has incompatible architecture

### ISSUE THREAD

**Issue by Knight1** [JonasProgrammer/docker-machine-driver-hetzner#105]
```
ERROR: Error creating machine: Error in driver during machine creation: could not create server: image has incompatible architecture (invalid_input)  driver=hetzner name=runner-XXXX-runner-XXX-XXX operation=create
```

Hetzner Cloud introduced arm64 Support. But sadly, when you specify type caxYY with image "ubuntu-20.04" it defaults to x86. 
https://github.com/hetznercloud/cli/blob/main/internal/cmd/image/describe.go#L23

Currently you have to get the current Image ID from the hcloud cli with arch arm64 for the corresponding image ID to use arm64. 

More like an FYI if someone has the same problem. Still might be a good thing to get the right image in the first place.

**Comment by JonasProgrammer** [comment]
Thanks for bringing this up

Well, given they also introduced [support for architecture filtering](https://github.com/hetznercloud/hcloud-go/pull/249/files#diff-f9547211e2ad8cf9e010e6d9bdc8a31ee36dbb0df47a73effb226c2152602ea1R146) I don't think implementing this should be too much of a problem. I'll have a look soon.

**Comment by JonasProgrammer** [comment]
Could you give 3.13.0 a shot, once it has finished building? Should work out-of-the-box now, but you may additionally override the image search architecture using `--hetzner-image-arch`.
