### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tniebergall** [JonasProgrammer/docker-machine-driver-hetzner#109]
I've launched a fresh ubuntu 22.04 server at hetzner an followed the installation instructions of your repo and the one of docker machine.

When I try to create a new machine with docker-machine, the precheck will fail.

`docker-machine  --debug create --driver=hetzner --hetzner-api-token="******" --hetzner-server-type="CX21" test`

**Output**

<img width="1460" alt="Bildschirmfoto 2023-07-17 um 22 20 55" src="https://github.com/JonasProgrammer/docker-machine-driver-hetzner/assets/1748788/49f2bc20-1fc7-4f23-8d06-6a0ea606ee12">

I've tried the original docker-machine binary and the one from gitlab

- https://github.com/docker/machine/releases/tag/v0.16.2
- https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/releases/v0.16.2-gitlab.21

Steps to reproduce

- Create a new cloud server at hetzner with ubuntu 22.04
- Install your docker-machine-driver-hetzner
- Install docker-machine

If you need any further details or wan't to get access to the testserver let me now.

**Comment by JonasProgrammer** [comment]
Hi,

sorry for the inconvenience, the architecture lookup was introduced only recently. I guess I got some things mixed up in the latest release, I'll check and come back to you as soon as possible.

**Comment by JonasProgrammer** [comment]
Kk, got down to the cause: `CX21` is not a valid server type, it should be `cx21`.

However, upon lookup for an unknown name, `nil` is returned and no error is raised (as per documentation, but parts of the code predate the official hcloud package -- it just so happened that the architecture lookup is the first place to use the server), which in turn causes the segmentation violation. I'll try to get a fix out for that behavior asap, but you should be good supplying the proper server type name.

**Comment by tniebergall** [comment]
Thank you sooo much.

With cx21 everything works as expected. What a lousy mistake by myself  🤦🏻‍♂️

**Comment by JonasProgrammer** [comment]
No problem, the lack of a proper error message with the driver binary crashing is misleading as well.

**Comment by tniebergall** [comment]
Another thin, the kink to the server types in the README does not exist anymore, the new one is https://docs.hetzner.cloud/#server-types-get-all-server-types

And also maybe a hin would be nice, because Hetzner itseld uses uppecases in the UI. I think that was the reason leading me to the uppercase usage.

<img width="268" alt="Bildschirmfoto 2023-07-17 um 22 53 32" src="https://github.com/JonasProgrammer/docker-machine-driver-hetzner/assets/1748788/963785c7-9ec8-4e35-a929-577512dd3cb6">

**Comment by JonasProgrammer** [comment]
> Another thin, the kink to the server types in the README does not exist anymore, the new one is https://docs.hetzner.cloud/#server-types-get-all-server-types

Thanks, I'll update it accordingly.

> And also maybe a hin would be nice, because Hetzner itseld uses uppecases in the UI. I think that was the reason leading me to the uppercase usage.

I do get the idea here, but I'm not sure the driver should be the one to decide (or lowercase stuff by default etc.). In contrast to images and so on the type is less likely to change, but I do not really want to have to touch the code if Hetzner ever decides to change their naming scheme. Perhaps we can escalate that to Hetzner as a suggestion for a more lenient name matching.

**Comment by tniebergall** [comment]
Something like the disclaimer is exactly what im meant.

I'm on your point, thats not realy a solid solution if the driver decides such things.

Thank you for your fast reply.
