### ISSUE TITLE
Use existing ssh keys without the parameter hetzner-existing-key-path

### ISSUE THREAD

**Issue by blar** [JonasProgrammer/docker-machine-driver-hetzner#12]
When new servers are created, existing SSH keys can be used. These can be passed by id or name.  Currently, the parameter hetzner-existing-key-path is required, which is not needed by the API in this case, to use existing keys.

https://docs.hetzner.cloud/#resources-servers-post

**Comment by JonasProgrammer** [comment]
You're right, the API itself doesn't need to know the existing key path.

The path is needed for docker-machine however, so it can copy the key to the machine's directory. Not having the private part wouldn't allow docker-machine to connect to the freshly created server and docker wouldn't be installed. I don't really see a defect here, as this is the solely purpose of docker-machine.

Could you maybe elaborate further on how you think machine propagation would work without the existing key?

**Comment by JonasProgrammer** [comment]
Closed due to lack of response.
