### ISSUE TITLE
Hetzner Cloud Volumes support

### ISSUE THREAD

**Issue by sannysoft** [JonasProgrammer/docker-machine-driver-hetzner#17]
Hetzner started volumes beta test. It would be great if this can be added as a persistent storage to rancher.
Details: https://www.hetzner.com/news/10-18-cloud-volumes/

**Comment by JonasProgrammer** [comment]
I like the idea in general, but as far as my understanding goes, volumes are usually managed by a separate volume driver.
Now we could add options to create one or more volumes during server creation and attach them, but aside from putting /var/lib/docker on a volume, I don't really see a point in offering this as part of the provisioning. Instead, having a volume driver that allows something like `docker volume create --driver hetzner --hetzner-volume stuff stuff1`, which in turn uses or creates a `stuff` hetzner volume and puts a `stuff1` folder on there, makes more sense IMHO.

If I'm missing the point, feel free to direct me towards the right idea, but as far as I see this now, this is beyond the scope of a machine driver.

**Comment by Negashev** [comment]
For example to create rook.io node with auto discovered free attached disk and make osd

**Comment by JonasProgrammer** [comment]
As previously stated, I still think the request is for a feature that's beyond the scope of a machine driver.

However, have a look at what GitHub recommended me today:
https://github.com/costela/docker-volume-hetzner

While I currently don't see a way to do this during auto-provisioning, it should be relatively easy to setup after initial provisioning.
@sannysoft would this be sufficient for your use case or are there valid reasons for why the machine driver would have to create and administer the volume?

**Comment by anebi** [comment]
I was testing https://github.com/stevenklar/kubernetes-hetzner-storage with Rancher 2.1 and it worked quite well. I am going to test it with 2.1 too, but I expect to work without problems too.

**Comment by anebi** [comment]
I think that this is even better: https://github.com/hetznercloud/csi-driver

**Comment by mxschmitt** [comment]
Closed due that's no `docker-machine-driver` related feature. You can already use the tools linked in the upper comments.
