### ISSUE TITLE
Removing machines that have already been deleted leaves its SSH key

### ISSUE THREAD

**Issue by mhutter** [JonasProgrammer/docker-machine-driver-hetzner#18]
How to reproduce:

1. Create a new machine named `worker1` using docker-machine
2. Remove VM `worker1` via the Hetzner console (or cli)
3. Remove machine using docker-machine
4. Create a new machine named `worker1` using docker-machine

Expected result: A new machine is created

Actual result:
> Error creating machine: Error in driver during machine creation: could not create ssh key: SSH key name is already used (uniqueness_error)

**Comment by mhutter** [comment]
This is because if [any of this](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/master/driver.go#L338-L349) fails, the SSH key is left behind

**Comment by JonasProgrammer** [comment]
So I have just attempted to fix the problem the way you described: I made the key-removal code execute regardless of the server removal's success.
This apparently does not work, however, as docker-machine (for me at least) crashes before it even reaches the `Remove` method with the error message `error removing host "somemachine": read tcp 127.0.0.1:57198->127.0.0.1:57197: wsarecv: An existing connection was forcibly closed by the remote host`.

To be honest, I have no idea how to properly deal with this or whether a driver can even handle that.

**Comment by heinrichmartin** [comment]
my2c: deleting a private key after an exception should be guarded by user approval (interactive or --force)

Let's assume the machine was not deleted before, but the deletion failed for another reason. Now, we are stuck with a machine that we cannot even access. Maybe provide a dedicated command, e.g. cleanup or remove-key.

**Comment by mhutter** [comment]
@JonasProgrammer from trying out a few things I suspect there are a few issues with the hcloud-go library; for example querying for a non-existing server does not return an error.

@heinrichmartin since we wanted to delete the machine anyway, this should not be an issue. I also think that to diagnose or fix machine removal we do not have to access the VM itself, since the removal process does not access the machine itself.

**Comment by mhutter** [comment]
I have opened hetznercloud/hcloud-go#99 to address the "not found" issue. Fixing this upstream would also catch a lot of Segfaults due to nil pointer references in docker-machine-driver-hetzner.

**Comment by heinrichmartin** [comment]
> since we wanted to delete the machine anyway, this should not be an issue. I also think that to diagnose or fix machine removal we do not have to access the VM itself, since the removal process does not access the machine itself.

I know it sounds weird, but accidentally losing a private key is nothing that I want to face. Right now, I can think of two possible scenarios - neither is implemented in the Hetzner API (yet?).
* Hetzner could provide an option to "lock" a server.
* Hetzner could provide a safe-guard for "active" servers (however this is defined, e.g. running, CPU or other KPI).

They would fail delete operations (among others) on such servers (unless forced). Now, I have no access to my server that was explicitly or implicitly protected from deletion.

**Comment by heinrichmartin** [comment]
Just to relax my comment: it is safe to cleanup the key, when we have confirmation that the server no longer exists (see pull requests).

> This is because if [any of this](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/master/driver.go#L338-L349) fails, the SSH key is left behind

This was the comment that alerted me. I assumed you wanted to ignore any failure state and delete the key anyway ...

**Comment by mhutter** [comment]
> accidentally losing a private key is nothing that I want to face

I totally get you :-) However, Hetzner only stores the _public_ key - the private key is fully managed by docker-machine.

> I assumed you wanted to ignore any failure state and delete the key anyway ...

This was indeed what I initially was going for. However, it makes more sense to only remove SSH key when server removal fails due to the fact that the server already is gone. This should also handle cases when server removal fails due to the server being "locked" - in that case `Remove` would return early, before removing SSH keys.
