### ISSUE TITLE
CLI option to determine version of driver binary

### ISSUE THREAD

**Issue by cyclux** [JonasProgrammer/docker-machine-driver-hetzner#25]
Recent update led me to try identifying the specific version of the binary.
However, executing `docker-machine-driver-hetzner -v` or similar just resulted in a notice that this plugin binary is not meant to be executed directly.

It would be nice if the CLI options `-v` or `--version` would return the current version of the binary or at least if it would be included into the mentioned notice text.

Or maybe there is another way to determine the version of the plugin via `docker-machine`? ` docker-machine create --driver hetzner --help` also did not include the version.

**Comment by mxschmitt** [comment]
@JonasProgrammer what do you think about this feature request? I could try to implement it.

**Comment by JonasProgrammer** [comment]
I think adding a `--version` flag that gets checked before yielding control to the driver's main routine is the best option. It's obviously not as convenient, but I don't think there is a predefined way in `docker-machine` to get driver versionss and vendoring the driver helper solely for the purpose of changing the NOTICE stuff won't do good in the long run.
