### ISSUE TITLE
Push upstream into docker machine

### ISSUE THREAD

**Issue by LKaemmerling** [JonasProgrammer/docker-machine-driver-hetzner#29]
Hello guys,

what would you think about pushing this machine driver to docker machine directly so it is "built-in"? https://github.com/docker/machine/tree/master/drivers 

Pro: Users won't need to download the driver on there own
Pro: This would be an official docker driver
Pro: Documentation would be available in the Docker docs.

**Comment by JonasProgrammer** [comment]
While it would be cool to see this project make it into upstream docker, I'm not sure we really qualify for official inclusion. We don't have tests at all and the code is mostly undocumented.

Granted, the logic is not very complex, but I doubt the docker people would want something like this in their codebase. Currently I don't have time to get this into an includable state. Perhaps that's something for the semester vacation...

This aspect aside, it actually takes ages to get something accepted into docker. Just listing our driver took more than half a year (see #7). So even if we decide to get this into a state that might be included, you guys shouldn't hold your breath to list hetzner cloud as docker-native any time soon ;)

**Comment by mxschmitt** [comment]
I would just go for adding some of our documentation to the official one. Linode for example does this, the driver of them is located in their own repository but the documentation is i the official docs. Or just at least some backlinks.
Reference: https://docs.docker.com/machine/drivers/linode/

**Comment by alexandernst** [comment]
Anyways, isn't the docker-machine repo in maintenance-only mode?

**Comment by mxschmitt** [comment]
Good catch. Let's close this one. Ref: https://github.com/docker/machine/issues/4537
