### ISSUE TITLE
Provide binary as releases

### ISSUE THREAD

**Issue by maxibanki** [JonasProgrammer/docker-machine-driver-hetzner#3]
Hi,
first of all, I would like to thank you for creating this project. 👍
It would be super cool, if you could provide the binary with the machine driver as releases, so that it can be downloaded directly. (maybe via [travis-ci](https://docs.travis-ci.com/user/deployment/releases/)?)
That's because e.g. [Rancher](https://github.com/rancher/rancher) can add custom docker machine drivers via a download URL.
Other drivers for references are e.g. [ecl](https://github.com/mittz/docker-machine-driver-ecl/releases) or [scaleway](https://github.com/scaleway/docker-machine-driver-scaleway/releases).
In the meanwhile (finished), I'm creating the UI part for the 100% compatibilty in Rancher [here](https://github.com/maxibanki/ui-driver-hetzner).
If you need any help for setting up travis-ci, I can help you. :)
Best regards
Max

**Comment by monochromata** [comment]
https://docs.travis-ci.com/user/deployment/releases/ documents how to release to Github using Travis. I might give it a try it out in my fork.

**Comment by JonasProgrammer** [comment]
Well, I cannot look into it till thursday, so if you could have a look, @monochromata, it'd be much appreciated

**Comment by maxibanki** [comment]
Maybe some tools / commands, which could help you:
- `mkdir releases`
- https://github.com/mitchellh/gox => `gox -output="releases/{{.Dir}}_{{.OS}}_{{.Arch}}/{{.Dir}}"` (creates the binary files of all architectures)
- `find releases -maxdepth 1 -mindepth 1 -type d -exec tar -cvzf {}.tar.gz {} \;` (creates tar.gz archives of the gox output binary folders and strips the first directory)
- add all `releases/*tar.gz` to the GitHub release

**Comment by monochromata** [comment]
Ok, thanks to Max' help, I created a first release with binaries from Travis: https://github.com/monochromata/docker-machine-driver-hetzner/releases/tag/0.2.3

There are a number of open points left:
* Add version number (from tag) to tar.gz file names
* shorten the path in the tarball (currently: releases/docker-machine-driver-hetzner_<os>_<arch>/docker-machine-driver-hetzner)
* I didn't test the tarball yet
* The README needs to be adjusted

**Comment by maxibanki** [comment]
Hi,
That's super cool :)
I've created PRs for adding the version number to the tar archive and stripping the path away in the tarball. When you create a test release, I can test it with Rancher to check if it works fine.
Tomorrow I will also add some documentation to the readme.
Best regards
Max

**Comment by monochromata** [comment]
Great: https://github.com/monochromata/docker-machine-driver-hetzner/releases/tag/0.2.4

* I now tried the linux/amd64 binary and was able to use it :-)
* The tarball is fine except it now contains a directory called "." I didn't find a quick work-around for that.

**Comment by maxibanki** [comment]
Both should be fixed with the PRs in your repository. :)

**Comment by monochromata** [comment]
Ok, it's done so far. The tar command is a bit ugly now (it outputs error messages because I added an extra docker-machine-driver-hetzner.exe which is missing for Unix builds, while docker-machine-driver-hetzner is missing for the Windows builds), but it works :-).

Thanks again, Max!

**Comment by maxibanki** [comment]
@monochromata Thanks to you too, it was a lot of fun. So should open source development be in 2018 👍
