### ISSUE TITLE
Error in driver during machine creation

### ISSUE THREAD

**Issue by carloslozano** [JonasProgrammer/docker-machine-driver-hetzner#40]
**Problem**
Use docker-machine create with the driver to create a server in Hetzner, optionally specifying a server location from the Hetzner API.

**Expected Behaviour**
A ssh key is added to the account related with the api token. A machine is created. The machine can be seen from the Hetzner Console and used. 

**Actual Behaviour**
A ssh key is added to the account related with the api token. An unknown error is reported by docker-machine driver. The ssh key is deleted from the account.

```
# docker-machine create --driver hetzner --hetzner-api-token=<token> --hetzner-server-location hel1 lala
Running pre-create checks...
Creating machine...
(lala) Creating SSH key...
(lala) Creating Hetzner server...
(lala)  -> Creating server lala[3146171] in create_server[28211794]
Error creating machine: Error in driver during machine creation: could not wait for action: Creating server failed because of an unknown error. (unknown_error)
```

**Docker Version**
```
# docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Wed Jul  3 12:13:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:31:12 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Docker Machine**
```
# docker-machine version
docker-machine version 0.16.0, build 702c267f
```

I've used this driver in the past, both with docker-machine and using Rancher 2.x, so I know it worked in the past. I've tested the aforementioned on an Ubuntu 18.04 and MacOS 10.14.6, both with the same error. Perhaps there are some breaking changes in the Hetzner API?

**Comment by imerr** [comment]
Getting the same error here

**Comment by imerr** [comment]
Seems to be hetzner related as we can't manually create servers either and not an issue with the driver

**Comment by carloslozano** [comment]
I've tested the same use-cases this morning (8:00 CET) and everything is working as expected.
The driver is working both standalone with docker-machine and also in Rancher as a node driver.

I guess Hetzner was having a rough weekend 😆
