### ISSUE TITLE
How to make it work on mac?

### ISSUE THREAD

**Issue by angelch94** [JonasProgrammer/docker-machine-driver-hetzner#41]
Before anything, thank you for your amazing work! This library may be so useful for some of us.

I would love to use it but in the compiled binaries i dont see any distribution for MAC, its probably one of them but i don't seem to know which one. How can i make it work for apple's ecosystem?

Thank you in advance guys!

**Comment by monochromata** [comment]
Try the binaries with OS darwin.

**Comment by Micromegass** [comment]
Hi @angelch94 ! Did you get this to work on Mac OS? @monochromata, I tried with OS darwin but  I get an ``exec format error``

**Comment by 0xsven** [comment]
> Hi @angelch94 ! Did you get this to work on Mac OS? @monochromata, I tried with OS darwin but I get an `exec format error` and with an older version ` bad CPU type in executable`

Similar issue:
```
Error starting plugin binary: fork/exec /usr/local/bin/docker-machine-driver-hetzner: bad CPU type in executable
Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
```

**Comment by JonasProgrammer** [comment]
@0xsven Which download link did you use? The one in the README points to the Linux-AMD64 versions.

Artifacts for other architectures are to be found [here](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/latest). From the nature of the question I guess you are on OSX, therefore you probably need the `darwin_amd64` build.

**Comment by 0xsven** [comment]
@JonasProgrammer You are right. I picked the wrong one. Somehow "AMD" has confused me I think. Thanks for the project. Love it.
