### ISSUE TITLE
Error setting machine configuration from flags provided: gob: name not registered for interface: "*rpcdriver.RpcFlags"

### ISSUE THREAD

**Issue by mcicolella** [JonasProgrammer/docker-machine-driver-hetzner#46]
Hi,
I'm trying to use your driver but I have the following error when I execute

`
HETZNER_API_TOKEN=XXXXXXXXXXXXXXXXXXXXXXX \
  && HETZNER_IMAGE=centos-7 \
  && docker-machine create \
     --driver hetzner \
     test-machine
`
Any idea?
Thanks

**Comment by JonasProgrammer** [comment]
Hi,

that looks rather strange indeed.

Could you please tell us your exact version of `docker-machine`; apparently this error can occur due to version incompatibilities.

**Comment by mcicolella** [comment]
Fixed with the last version of docker-machine.
Thanks for your great work!
