### ISSUE TITLE
Support Hetzner Cloud Load Balancers

### ISSUE THREAD

**Issue by Atomzwieback** [JonasProgrammer/docker-machine-driver-hetzner#48]
Just saw that Hetzner has now Cloud Load Balancers (beta). Would be a nice addition for the rancher driver as well at some point.

Info: https://www.hetzner.com/news/07-2020-load-balancer/

Product Page: https://www.hetzner.com/cloud/load-balancer

Cloud Controller: https://github.com/hetznercloud/hcloud-cloud-controller-manager

**Comment by JonasProgrammer** [comment]
Hi,

I only just now had a look at this feature, but to me, it is unclear as to how `docker-machine` should be involved with the creation and use of load balancers.

As for balancer creation, the vast amount of configuration options makes this not a feasible option IMO. We'd either end up rebuilding the `hcloud` cli in the driver's command line flags or have some unflexible defaults, rendering it effectively useless.

The only valid action I can think of is attaching a machine to an existing balancer upon creation, but even then this is some one-liner with the existing [cli](https://github.com/hetznercloud/cli) -- which you'd probably want to use anyway before and afterwards, for service configuration etc.

Perhaps I just don't see the usecase yet, but to me it seems out-of-scope. LBs can exist independently of a `docker-machine`-provisioned cloud server and service definitions are a higher-level concept -- either being managed automatically using kubernetes and the controller manager you linked or manually with the cli.
