### ISSUE TITLE
Rancher 2.5.1 fails to install driver

### ISSUE THREAD

**Issue by morremeyer** [JonasProgrammer/docker-machine-driver-hetzner#51]
On Rancher 2.5.1, installation of the driver [with the UI driver by mxschmitt](https://github.com/mxschmitt/ui-driver-hetzner) fails with:

```
[INFO] Download https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/2.1.0/docker-machine-driver-hetzner_2.1.0_linux_amd64.tar.gz
[ERROR] error syncing 'kd-rqwlc': handler mgmt-kontainer-driver-lifecycle: failed to find driver in archive. There must be a file of form kontainer-engine-driver-*, requeuing
```

This happens with versions 3.0.0 and 2.1.0 on rancher 2.5.1.

I therefore repackaged the .tar.gz, renaming the file to `kontainer-engine-driver-hetzner` to check if this was the error.

This downloads and installs the driver correctly, but then outputs:

```
This is a Docker Machine plugin binary.
Plugin binaries are not intended to be invoked directly.
Please use this plugin through the main 'docker-machine' binary.
(API version: 1)
```

Afterwards, there is no hetzner provider when using `Clusters --> Create cluster`.

If I can help with anything further, let me know :)

**Comment by JonasProgrammer** [comment]
Well, the binary inside the archive is named `docker-machine-driver-x`, as mandated by `docker-machine`. I don't know anything about rancher, but it seems they mandate a different filename scheme.

While I could in theory change the build to accomodate for this, this would render the binary unusable with `docker-machine`, i.e. its original purpose.

For now I'm gonna call this out-of-scope, as this solely seems to be ranger-related. Still, I'll keep this open for now.
@mxschmitt as the ranger expert, do you have any input on this?

**Comment by morremeyer** [comment]
After crosschecking everything 5 times before opening this ticket, I immediately noticed my fail: I tried to create a `cluster` driver, not a `node` driver in rancher.

Thanks @JonasProgrammer for the fast response. But as this is clearly a user error, I’m closing it. Sorry for the disturbance.
