### ISSUE TITLE
Issues with node creation

### ISSUE THREAD

**Issue by mschickervxob** [JonasProgrammer/docker-machine-driver-hetzner#52]
Setup: Rancher 2.4.5 with Hetzner Machine driver 1.x (cant remember the exact version)

I can't remember the exact flow, but somehow this is the story:
- A node failed. Deleted it on Rancher. On reprovisioning the hostname was already taken *uniqueness_error
- Hetzner had an issue with machines deployment in Nuremberg datacenter
- I changed the machine driver to 3.0.0
- Changed the template to use Falkenstein
- Reprovisioning failed with SSH key name is already used (uniqueness_error) 
- Created complete new template
- Created a second pool with new template
- Getting Error setting machine configuration from flags provided: --hetzner-image and --hetzner-image-id are mutually exclusive; Timeout waiting for ssh key
- Tried to change the template via API - regardless what I change via API it stays the same and shows completely different stuff then on UI ( UI Ubuntu 18.04 - API Ubuntu 16.04 and ID set)
- Downgraded to https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/2.1.0/docker-machine-driver-hetzner_2.1.0_linux_amd64.tar.gz
- Same issues stay

Questions:
- Is the different machine driver used at all?
- How to fix the issues ? :-)

Thanks.

**Comment by JonasProgrammer** [comment]
Hi, sorry for the issues you encounter.

> Is the different machine driver used at all?
An easy test for this would be to simply rename the machine driver binary -- if no error regarding a missing executable occurs, then most likely no, the different driver is not used.

> How to fix the issues?
Sounds mostly like a ranger problem to me, but could you perhaps try and create the node manually using only `docker-machine` and the SSH key, image ids etc. you want? If that works, the error is somewhere else, if not, could you provide a full log of the provisioning output somewhere please?

**Comment by mschickervxob** [comment]
Thanks for the quick reply. I will try to get the infos from the rancher instance.

**Comment by smirnov-mi** [comment]
I'm facing a very similar issue.
I was the hetzner-driver v2.1.0 withing Rancher, saw this error while automatic re-creating new nodes BUT for Datacentres Nuremberg and Falkenstein.
I updated the driver to the v3.7.1 but still got the same error.
So I got the cluster created with a few nodes, but unable to add new nodes just yet.
