### ISSUE TITLE
SSH Key for debugging?

### ISSUE THREAD

**Issue by sokraflex** [JonasProgrammer/docker-machine-driver-hetzner#53]
Greetings,

first of all: Thanks a lot for sharing the code! The driver has been very useful 👍 🥇 

I'm currently receiving errors and would like to SSH into the created machine to debug the errors further. Is it possible to add an additional SSH key to the machine? E.g. in [hcloud-cli](https://github.com/hetznercloud/cli), it's possible to supply multiple `ssh-key` parameters:

```
./hcloud server create \
	--name test \
	--image ubuntu-20.04 \
	--type cx11 \
	--ssh-key "debugging" \
	--ssh-key "locally-generated-key"
```

Kind regards

**Comment by JonasProgrammer** [comment]
Should work now in 3.1.0
