### ISSUE TITLE
[Proposal] Add argument/option to set hetzner cloud labels on servers

### ISSUE THREAD

**Issue by ricktap** [JonasProgrammer/docker-machine-driver-hetzner#56]
Hi,

I‘m using this great driver with rancher, to create k8s clusters, that are behind a load balancer. The load balancer finds the servers either by name or even better, by tags. To automatically have newly created instances assigned to the load balancer, I would need a way, to have those tags be created by the docker-machine driver, I propose the —hetzner-label option, that could be specified multiple times, like this

`—hetzner-label “cluster=staging” —hetzner-label “tier=nvme”`

thanks for the great work. This driver really made our k8s cluster deployments a lot easier.

**Comment by JonasProgrammer** [comment]
Hi,

just so we are on the same page: By 'label' you refer to Hetzner server labels, as described [here](https://docs.hetzner.cloud/#servers-create-a-server)? If so, that should be straight forward to implement and I will gladly add this feature.

Sorry if the question is a little silly, but with 'label' in the context of Docker, Hetzner and Cloud stuff in general being about as overloaded as `static` in C++, I want to make sure not to implement something you did not want with an option name you proposed for something different.

Have a great NYE

**Comment by ricktap** [comment]
Hi and happy new year! Yes, that's exactly the label I meant. You are absolutely right, the term label might be a bit overloaded, so maybe --hetzner-server-label would be a better name for that option. thanks and have a great day

**Comment by JonasProgrammer** [comment]
Should work as of 3.2.0. Thanks for the suggestion!

**Comment by ricktap** [comment]
Works like a charm. Thank you very much!
