### ISSUE TITLE
Pakcaging of the driver

### ISSUE THREAD

**Issue by qubusp** [JonasProgrammer/docker-machine-driver-hetzner#62]
Hello, is it possible to pack the driver with execution permissions already?

**Comment by JonasProgrammer** [comment]
Hi,

just checked and both the Darwin 64 and Linux AMD64 drivers are packaged with the executable permission set.

Which operating system are you on? Or are you referring to the (seemingly outdated) steps in the README?

**Comment by qubusp** [comment]
I am on Ubuntu 18.04, I think I am reffering to them, yes. But my problem is with the combined usage in Rancher where it seems not to be able to pick it up because of execution permissions or something like that.

**Comment by mxschmitt** [comment]
I think the majority of the users of this project is using it with Rancher without any issues, could you maybe take a look in your Rancher logs, maybe it gives you a hint whats going wrong.
