### ISSUE TITLE
Set networks and serverLabels as public fields

### ISSUE THREAD

**Issue by jmatsushita** [JonasProgrammer/docker-machine-driver-hetzner#64]
Hi there,

A couple of issues in the `terraform-rancher2-provider` would be able to move forward if the following fields where marked as `public` so that they can be marshalled/unmarshalled:
 - [`networks`](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/master/driver.go#L42) https://github.com/rancher/terraform-provider-rancher2/issues/656
 - [`serverLabels`](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/master/driver.go#L46) https://github.com/rancher/terraform-provider-rancher2/issues/657

If there aren't any reason for the other fields to be `private` I would also suggest exporting:
 - `userData`
 - `volumes`
 - `firewalls`
 - `additionalKeys`

Happy to submit a PR if you agree with the intent here.

Thanks,

Jun

**Comment by jmatsushita** [comment]
To clarify, this would be used in the following way by the terraform provider https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/node_template#hetzner_config

**Comment by JonasProgrammer** [comment]
Hi,

I've implemented the requested changes on a feature branch for now. Could you please try out the artifacts [here](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/actions/runs/890759039) and see if they fit your needs?

I have added the other requested items as well, except the user-data. IMO this field is more likely to contain secret information than the others, so I personally would prefer to keep it only when needed -- i.e. during the creation. I'm open for discussion, however.

Cheers

**Comment by stefandanaita** [comment]
Hi @JonasProgrammer, any chance the server labels will make it into the main branch? There's no reason not to and it would make creating label selector load balancers much much easier.. Thank you!

**Comment by stefandanaita** [comment]
Nvm, I was using an older version. Sorry!

**Comment by JonasProgrammer** [comment]
@stefandanaita Hi and no worries about that. I still merged the feature branch, just in case someone may find it useful in the future. Could you maybe give the [this manual build](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/actions/runs/1720545304) a try (or build from `master` yourself if you prefer)?
If everything still works as expected, I'll be happy to release a 3.6.0 tomorrow.

**Comment by stefandanaita** [comment]
Worked fine for me by building from master 👀

**Comment by stefandanaita** [comment]
Hey @JonasProgrammer! Any chance you can release 3.6.0? 😄

**Comment by JonasProgrammer** [comment]
Done :)

**Comment by stefandanaita** [comment]
Thank you sir! 🙏🏻
