### ISSUE TITLE
External dns issue

### ISSUE THREAD

**Issue by AdZoAi** [JonasProgrammer/docker-machine-driver-hetzner#65]
Hi there,

We had a rancher single deploy 2.4.5 cluster on Hetzner all ubuntu 18.04 servers & using v 2.0.1 of this driver, & working fine!

We updated to ubuntu 20.04 & rancher 2.5.7 (also2.5.8) &  docker-machine-driver-hetzner 3.2.0; with this setup external-dns is no able to update external DNS in cloudflare anymore!.

This same new setup (rancher 2.5.8/ubuntu 20.04 ), but with old docker-machine-driver-hetzner version 2.0.1  works! 

Many Thanks !

**Comment by JonasProgrammer** [comment]
Hi,

first of all, sorry for the inconvenience the latest driver versions cause you.

I  have limited kubernetes experience and pretty much none regarding ranger, so I am not sure I can help alot. Judging from a [comparison](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/compare/2.0.1..3.2.0) of the versions mentioned, however, the only relevant that has changed is regarding private networks and existing SSH keys.

Perhaps you could try and play around with the options introduced a bit and see if it helps?

Cheers
