### ISSUE TITLE
Nodes aren't started

### ISSUE THREAD

**Issue by realulim** [JonasProgrammer/docker-machine-driver-hetzner#68]
I've provisioned a cluster with Rancher 2.5.8 and the latest node driver 3.3.1 and the servers were created in the Hetzner Cloud console, but not started. I waited for about 20 minutes, but nothing happened - Rancher patiently waited for the created nodes to become available. Once I started the servers manually from the Hetzner Cloud console, the cluster installation proceeded and everything seems to work now.
Perhaps there is some configuration option that servers are always created as inactive by default?

**Comment by realulim** [comment]
I've let cluster creation go on and the nodes that I manually started are shut down again. It appears Rancher is shutting them down for some reason.

**Comment by realulim** [comment]
Further insight reveals that the nodes are created without an interface to the 10.0.0.0/16 network, despite having selected that private network in the node template. Therefore Rancher has no way of even connecting to these nodes, but I still don't understand why Rancher shuts them down, after I start them manually.

**Comment by JonasProgrammer** [comment]
Hi,

sorry for the inconvenience the driver is causing you. From the driver's perspective, machine creation, starting instances and shutting them down are distinct operations its RPC interface has to expose.

I'm unfamiliar with the Rancher side of things, but could you perhaps try to create a machine manually using `docker-machine` and setting appropriate flags to create the private network and use it for communications? Ideally from another cloud instance on the same network, as to allow the whole provisioning process to run (if that is feasible for you from the cost perspective). If that fails as well, perhaps something in the `hcloud` API changed or we introduced a regression some time ago that nobody noticed has noticed yet. On the other hand, if that works fine, something is going wrong down the line with ranger.

The driver binary itself is rather 'dumb' and does not do any fancy timeout stuff (or automatic shutdowns for that matter), so from the behavior you describe I can only guess that perhaps Rancher is giving up after some time and then calls the shutdown method on the driver to get rid of the servers -- although that would not really make sense, as `Destroy()` would be more appropriate here.

**Comment by realulim** [comment]
I don't think the driver is causing any problems. I thought so in the beginning, because I assumed the Hetzner Cloud would work like it always did. However, it appears that they actually introduced a bug a couple of days ago, which they are fixing right now. I'll report back once they fixed it.
Do you know of a way to watch the provisioning process via some logfile or other mechanism?

**Comment by JonasProgrammer** [comment]
`docker-machine` has a `--debug` flag that can be used with the `create` subcommand. That should output both the log information from the driver and the provisioning process itself.

**Comment by realulim** [comment]
Thanks and I close this issue, because Hetzner fixed something and now I cannot reproduce the problem.
