### ISSUE TITLE
[Feature] Allow defining labels for auto-created SSH Keys

### ISSUE THREAD

**Issue by JanKoppe** [JonasProgrammer/docker-machine-driver-hetzner#69]
This driver will create new SSH keys in the cloud project. Currently it's not possible to define any labels for these keys though. This is possible for servers (#56).

I would like to be able to use e.g. the config option `--hetzner-key-label` to define the list of labels, similar to `--hetzner-server-label`.

If you want, I could work on this and contribute that option, a quick glance at the code suggests that it should not be too difficult.

Code reference:
https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/1d32c6c2f293f8e693045f066cdb98db9bf3eaeb/driver.go#L520

**Comment by JanKoppe** [comment]
Sorry, seemed so easy, I just went ahead and did it. See my Pull request. :) Hope that works for you. Local testing seemed all fine, but I'm not successful in adding those labels via environment variables - but not for the server flags either. Maybe there's some special format required to pass on slices via env vars that I just don't know?

**Comment by JonasProgrammer** [comment]
Hi,

thanks for the suggestion and for quickly implementing it yourself (I'm currently away from home without a machine properly set up for go development, so this would have taken me a bit presumably). I'll merge the PR after everything has passed.

Regarding your environment problem: Please see [my comment](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/issues/37#issuecomment-515473092) on #37. Unfortunately environment variables for slice arguments are not being considered unless the option is also specified (taking precedence and therefore rendering them effectively useless). Unfortunately that's an issue of the underlying `libmachine` (for which development ceased with `docker-machine` IIRC), so I doubt we can easily fix that. As the driver is a separate binary communicating with the host `docker-machine` process via IPC simply switching to another arg parser is not really an option.

If you really do need to use environment variables, we either have to add another option with a non-slice type (perhaps `key-label-list`) and then split on ',' or something.

Sorry for the inconvenience.
