### ISSUE TITLE
Improve project visibility

### ISSUE THREAD

**Issue by monochromata** [JonasProgrammer/docker-machine-driver-hetzner#7]
Ok, so now that the plug-in is ready to be used, we could make others aware of it.
* @JonasProgrammer could add it in a pull request to https://github.com/docker/docker.github.io/blob/master/machine/AVAILABLE_DRIVER_PLUGINS.md
* @thcyron, @thetechnick: is it possible to hint at the driver in the Hetzner Cloud documentation?
* Anything else ...?

**Comment by thcyron** [comment]
We’re still in the process of figuring out what the best way is to promote all the libraries and integrations for Hetzner Cloud. We’d we glad to add this project to the list then.

**Comment by JonasProgrammer** [comment]
To be honest, I wouldn't consider this 'stable' as of now, thus I'm not sure whether I should actually PR this as a semi-official third party driver.

That being said, @monochromata and @mxschmitt, would you mind me adding you as contributors to this repository. I'd feel better if I'm not the only person who can respond to bugs, especially since I'm neither a good go programmer nor a docker expert beyond the 'user' part of it.

**Comment by monochromata** [comment]
Regarding the PR, I'd just try it. The list does not say that drivers should be stable in a certain way or official.

I'd be happy to become a contributor for this repo :-).

**Comment by monochromata** [comment]
@JonasProgrammer and @mxschmitt: Would you mind if I add all of us 3 to https://github.com/docker/docker.github.io/blob/master/machine/AVAILABLE_DRIVER_PLUGINS.md (including you e-mail addresses)? If not: What's your e-mail addresses?

**Comment by monochromata** [comment]
Ah, @JonasProgrammer should get 50 Euros worth of Hetzner credit according to https://docs.hetzner.cloud/#header-introduction-1 :-)

**Comment by JonasProgrammer** [comment]
jonass@dev.jsje.de for development related stuff. As for the EUR 50, I've already got them as soon as I found out you could, mostly due to realizing that testing the driver now indeed costs money in contrast to the good old beta times.

**Comment by mxschmitt** [comment]
My contact email is: max@schmitt.mx, good job :)

**Comment by monochromata** [comment]
The docker pull request has been merged and https://github.com/docker/docker.github.io/blob/master/machine/AVAILABLE_DRIVER_PLUGINS.md now lists our driver :-).

If that's all we want to improve project visibility for now, we can close the issue.

**Comment by JonasProgrammer** [comment]
I don't see anything else to do in terms of publicity as of now, so closing this is fine from my side.

Well yes, we could design a nice website and perhaps a logo with Martin riding a whale or something... but honestly, I think, being somewhere in Docker's list is sufficient.

**Comment by mxschmitt** [comment]
We could create a GitHub Pages website, which shows the README, that's very good for SEO and looks good I think. It will be completely auto generated which is nice.

**Comment by monochromata** [comment]
Cool, do you know how to do it, Max? :-)

**Comment by mxschmitt** [comment]
I unfortunately can't implement this, only the owner (@JonasProgrammer) of the repository is allowed to do that.

 ![image](https://user-images.githubusercontent.com/17984549/49470913-bdf3cb80-f80b-11e8-82ca-232c7b4df49a.png)

You have to enable the GitHub Pages in the repository settings [here](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/settings).

Afterwards it should be available under: https://jonasprogrammer.github.io/docker-machine-driver-hetzner

We should link once the page is available in the repository website:

![image](https://user-images.githubusercontent.com/17984549/49471204-9cdfaa80-f80c-11e8-8cfa-fa52087d1f0d.png)

**Comment by JonasProgrammer** [comment]
Done. Any wishes regarding the theme?

**Comment by mxschmitt** [comment]
I would prefer `Cayman` or `Architect`, @monochromata what do you think?

**Comment by monochromata** [comment]
I'm easy: I have no preference :-)

**Comment by JonasProgrammer** [comment]
Cayman it is, then.

**Comment by mxschmitt** [comment]
Cool, great job! We can close this issue now once you've added the link to the GitHub page 😺
