### ISSUE TITLE
[Question] Cluster autoscaling

### ISSUE THREAD

**Issue by fmendez89** [JonasProgrammer/docker-machine-driver-hetzner#74]
Hi Jonas,
thanks for your work with this node driver, is has been working great for the last two weeks in our environment. 
But we have been asking ourselves if there is any possibility to have autoscaling like the example with the autoscaler from the kubernetes repo.

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/hetzner/examples/cluster-autoscaler-run-on-master.yaml

On the example it sets the nodes type pools with the command  `` --nodes=1:10:CPX11:FSN1:pool1`` but I don't know if this would work with this node driver. Maybe I'm a little bit lost here though.

Best regards

**Comment by JonasProgrammer** [comment]
Hi Fran,

happy to hear that it has served you well so far.

There seems to be some confusion around what this driver (or `docker-machine` in general) can and cannot do. Basically, `docker-machine` only manages machines -- physical or virtual -- and helps provisioning them with a docker daemon. It does not have a higher-level abstraction of clusters or something alike (well, you can configure the provisioned docker daemon to join a swarm, but that is orthogonal to machine management).

Therefore the driver itself cannot provide any auto-scaling functionality or something like that: it merely implements the very basics, like machine creation, destruction etc. for `docker-machine` to do its thing. It does not know anything about any other servers in a project.

You could, however, write a separate tool that monitors your load and, if appropriate, adds or removes nodes using `docker-machine`. But if you do have such requirements, you're likely better of with something field-tested like kubernetes.

Sorry to disappoint here, let me know if I can be of any further help.

Best regards
Jonas

**Comment by fmendez89** [comment]
Hi @JonasProgrammer,
thanks again for your reply. Very helpful. We managed to get autoscaling working with the init script with a join command to the kubernetes cluster. But it just works when upscaling, because there is a bug with longhorn that prevents downscaling. But anyway, thanks for your work. 

Best regards
