### ISSUE TITLE
Creating clusters fails

### ISSUE THREAD

**Issue by crisrat** [JonasProgrammer/docker-machine-driver-hetzner#75]
I'm having issues provisioning RKE clusters (always fails at installing docker),
```[ERROR] error syncing 'c-wdlz9/m-h9dsx': handler node-controller: Error creating machine: Error installing Docker: , requeuing```
I've tried ubuntu 18 and 20, debian, fedora with the same outcome.
I've also tried it on digital ocean and all works fine.

My note driver and template are
```resource "rancher2_node_driver" "hetzner_node_driver" {
  active            = true
  builtin           = false
  name              = "Hetzner TF"
  ui_url            = "https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js"
  url               = "https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/3.5.0/docker-machine-driver-hetzner_3.5.0_linux_amd64.tar.gz"
  whitelist_domains = ["storage.googleapis.com"]
}

resource "rancher2_node_template" "hc_node_template" {
  name      = "hc-node-template"
  driver_id = rancher2_node_driver.hetzner_node_driver.id
  hetzner_config {
    api_token       = var.hcloud_token
    image           = "ubuntu-18.04"
    server_location = "nbg1"
    server_type     = "cpx21"
    # cloudinit       = ""
    use_private_network = false
  }
}


```

And also not able to provision RKE2 clusters - since it asks for a cloud credential - which it never saves so cannot proceed.
Should I provide screenshots or a recording (is that an issue just on my end perhaps?

Trying to add cluster I get this 
![image](https://user-images.githubusercontent.com/5023897/140588224-48e23b22-5a77-469f-a1b6-ea0e7fdf8e0a.png)

And after adding anything in there, it doesn't save and I get this
![image](https://user-images.githubusercontent.com/5023897/140588285-88894a04-fe5b-47d6-9a9f-7ce3a8a514bf.png)

And the box says "Sorry, no matching options"

**Comment by JonasProgrammer** [comment]
Hi and sorry this is causing you troubles.

I'm not familiar with RKE, but is there any way you can access the raw `docker-machine` logs in order to debug the issue? From the information provided my best guess is that there is no Hetzner API key being passed, but that's a very vague guess.

**Comment by crisrat** [comment]
Hi and thanks for your reply
Will try to find those (do you know where I can find them exactly?) - the above is from the pod logs, searched the whole disk for the VM id.
If it's because of the API key missing, I could get that for RKE2, where I can't actually add it. For RKE1, its never asked of me.
My node definition includes the api key...
So not sure how it's not there, because VMs are provisioned, just the software on them never installed and connecting to master node

**Comment by JonasProgrammer** [comment]
Hi,

sorry, unfortunately I have absolutely no experience with RKE, as stated. I'm pretty positive the log output is going somewhere, but I cannot give you any hints on that either.

For clarification: This driver is only the low-level part that does communication with Hetzner and -- when it works -- provides `docker-machine` with the means to get a `docker` instance up and running. I know that there is are some upstream projects reyling on this, like Max' Rancher driver, but I have no proper knowledge about any of them.

Perhaps you could first try to get help on how to extract logs from RKE and we can have a look at what is going wrong afterwards.

Regards

**Comment by crisrat** [comment]
Hi again,

Yeah, the machines are provisioned correctly.
Ah yeah, you're right, probably should've opened this ticket here : https://github.com/mxschmitt/ui-driver-hetzner
If that's the one you are referring to :)
