### ISSUE TITLE
Rancher not seeing errors during provisioning

### ISSUE THREAD

**Issue by blafasel42** [JonasProgrammer/docker-machine-driver-hetzner#76]
Hi, i don't know if this is a problem in rancher or in the machine-driver:
Today i specified wrong node names in rancher (including "_").
I got this error message in the Rancher Logs:

2021/12/25 07:20:52 [ERROR] error syncing 'c-t6qzt/m-2n74l': handler node-controller: Error creating machine: Invalid hostname specified. Allowed hostname chars are: 0-9a-zA-Z . -, requeuing

But rancher did not stop but re-tried endlessly without giving any error message. It was just waiting forever in the UI.
(i was using Version 3.3.0 of the machine driver)

Now that i know, i will always look in the logs when it takes too long, but maybe it is worth looking into it?

**Comment by JonasProgrammer** [comment]
Hi,

sorry for the inconvenience. I have just verified the driver binary properly emits an error in this case (and does so almost immediately), and `docker-machine` in turn exits with a non-zero exit code. So from my perspective, there is little that can be done driver-side, as the `docker-machine` side of things behaves properly -- I currently fail to see what more could be necessary to indicate the error status to Rancher.

Perhaps you could file an issue for the corresponding Rancher plugin and cross-link them, so we can discuss on what changes are necessary for more reliable error detection?

Best regards

**Comment by blafasel42** [comment]
Hi, thanks for the update. I will ask the same in the Rancher Slack channel now. Just wanted to start at the source ;)
