### ISSUE TITLE
Old Kubernetes versions

### ISSUE THREAD

**Issue by ukanwat** [JonasProgrammer/docker-machine-driver-hetzner#83]
I plan to install Kubernetes version 1.22, but the most recent version in the dropdown menu is v1.18.20-rancher1-1 which is pretty old. Am I missing something?

**Comment by JonasProgrammer** [comment]
Hi,

this is the low-level `docker-machine` driver interacting with Hetzner to create cloud servers and provision docker on them. It knows nothing about Kubernetes versions or anything, that kind of stuff is managed by upstream applications.

I got to know a little bit about Kubernetes, but still have no Rancher experience whatsoever. I am aware of [mxschmitt/ui-driver-hetzner](https://github.com/mxschmitt/ui-driver-hetzner), but even there I see no place to specify a kubernetes version.

What upstream tooling are you using exactly?

**Comment by ukanwat** [comment]
Ah right! I am using an older rancher version (v2.4.9) which might be the reason why there aren't any new Kubernetes versions in the menu. Thanks.
