### ISSUE TITLE
Choose another default image

### ISSUE THREAD

**Issue by monochromata** [JonasProgrammer/docker-machine-driver-hetzner#9]
* Currently, the default image does not work (in all cases): #8 
* Maybe use `ubuntu-16.04` by default because it has been reported to work and is similar to Debian.
* Also document the default values for the command-line options in README.md right in the line that contains the option, not after the list of options.

**Comment by mxschmitt** [comment]
Hi there, I think, `ubuntu` is a good choose, because when you are creating a virtual machine on the official hetzner cloud webinterface, there is also `ubuntu` selected as default.

**Comment by JonasProgrammer** [comment]
+1 for Ubuntu.

Back in cloud beta times, I originally chose debian solely for the reason that it is my preferred operating system (and fun fact: I've 2 roots and 1 vserver running debian 9 and docker 17.12 without any issues...) and it worked. The first point is not a valid argument and the second... ya.

The question is, does this now require a major version bump according to semantic versioning? In theory, at least, this is a 'breaking' change, although Ubuntu behaves debianish enough in most cases so one would not even notice...

**Comment by mxschmitt** [comment]
Yes, when we change the default distribution to `ubuntu` we need to bump the major version, because there could be incompatibles between the new distribution and the old one. 
So just to stick to the standards, I'd prefer that.

**Comment by monochromata** [comment]
Yup, incrementing the major version is fine. I had thought about a new issue to create a 1.0.0 version anyways :-). I'll create a commit that implements the changes proposed in this issue.

**Comment by monochromata** [comment]
Ok, 1.0.0 is out. I tested the files created by Travis for linux amd64.
