### ISSUE TITLE
driver does not remove public ip from node

### ISSUE THREAD

**Issue by makmarius** [JonasProgrammer/docker-machine-driver-hetzner#90]
Hi!
Thanks for this project, it really helped us out and I'm sorry to bother anyone with this.

A thing we would like to do, but seemingly can't is have private IP only machines. This may be somewhat related to #84, but according to some commenters it should be possible?

We're using `gitlab-runner`, but also the manual call fails so... maybe the `README.md` isn't as clear for us as it is for others.

```terminal
$ docker-machine create          \
  --driver=hetzner               \
  --hetzner-api-token=$API_TOKEN \
  --hetzner-server-type=cpx11    \
  --hetzner-disable-public       \
  --hetzner-use-private-network  \
  --hetzner-networks=my-local-network \
  local-network-test
```

The output then is as expected in the code:

```
Running pre-create checks...
Creating machine...
(ci-hetzner-test) Creating SSH key...
(ci-hetzner-test) SSH key not found in Hetzner. Uploading...
(ci-hetzner-test) Creating Hetzner server...
(ci-hetzner-test)  -> Creating server local-network-test[313373] in create_server[1337]
(ci-hetzner-test)  -> Server local-network-test[313373]: Waiting to come up...
(ci-hetzner-test) Wait until private network attached ...
(ci-hetzner-test)  -> Server local-network-test[313373] ready. Ip 10.0.0.3
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env local-network-test
```

I'm not very familiar with go but it seems [setPublicNetIfRequired](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/d1bec1ad93f21fa8d1bce90930fe866cdfc765cd/driver.go#L574) does not really work for my settings. Or am I misunderstanding the names?

I don't mind if there is a public IP for the setup that then gets removed, I just understand the settings I use in that way, that I'll end up with a machine not tied to a public IP (of any kind) and that is not what I'm ending up with. Any help is appreciated!

**Comment by JonasProgrammer** [comment]
Hi,

can you verify the machine actually has a public IP in the Hetzner web UI? I did touch this code recently to support primary IPs, so perhaps I screwed something up.

Also, could you maybe try [3.8.1](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/tag/3.8.1) and see if it works as expected there?

**Comment by makmarius** [comment]
Hi!

Sorry for the long wait, weekends 😅 

The driver doesn't seem to print a version (neither in `3.8.1` nor in `3.9.0`) for me. Both downloaded via the releases, but maybe I'm supposed to ask `docker-machine` for the version of the driver?

```
# /usr/local/bin/docker-machine-driver-hetzner -v
Version: 
# sha256sum /root/docker-machine-driver-hetzner_3.8.1_linux_amd64.tar.gz 
f53d57e06770da8a179463a34991a51b0b7c75d522a1d100de53b27c82530bcc  /root/docker-machine-driver-hetzner_3.8.1_linux_amd64.tar.gz
# sha1sum /usr/local/bin/docker-machine-driver-hetzner
009a131a76d48a2027d6e4c1833e7eaab7254514  /usr/local/bin/docker-machine-driver-hetzner
```

Anyway I'm reasonably sure I have `3.8.1` at this point, but still:

```
# docker-machine create \
  --driver=hetzner \
  --hetzner-api-token=$API_TOKEN \
  --hetzner-server-type=cpx11 \
  --hetzner-disable-public=true \
  --hetzner-use-private-network \
  --hetzner-networks=$LOCAL_NETWORK_ID \
  local-network-test
Running pre-create checks...
Creating machine...
(ci-hetzner-test) Creating SSH key...
(ci-hetzner-test) SSH key not found in Hetzner. Uploading...
(ci-hetzner-test) Creating Hetzner server...
(ci-hetzner-test)  -> Creating server local-network-test[31337] in create_server[1337]
(ci-hetzner-test)  -> Server local-network-test[31337]: Waiting to come up...
(ci-hetzner-test) Wait until private network attached ...
(ci-hetzner-test)  -> Server local-network-test[31337] ready. Ip 10.0.0.3
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with ubuntu(systemd)...
Installing Docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env local-network-test
```

Alas, still with public IP:

```
# docker-machine ls
NAME                 ACTIVE   DRIVER    STATE     URL                   SWARM   DOCKER      ERRORS
local-network-test   -        hetzner   Running   tcp://10.0.0.3:2376           v20.10.21   
```

![image](https://user-images.githubusercontent.com/37072046/203010754-bf17602a-d2e1-4086-9240-4c3fde6fce8d.png)

**Comment by JonasProgrammer** [comment]
> Hi!
> 
> Sorry for the long wait, weekends 😅

No worries there, I also may be slow to respond the next couple of days.

> The driver doesn't seem to print a version (neither in `3.8.1` nor in `3.9.0`) for me. Both downloaded via the releases, but maybe I'm supposed to ask `docker-machine` for the version of the driver?

Well, whatever this issue here brings to light, at least I can give you credits for finding #92 😅

> An important addendum might also be, that I'm not using the officially-abandoned `docker-machine` but [a maintained fork from GitLab](https://gitlab.com/gitlab-org/ci-cd/docker-machine).

Thank you for the info, that is definitely something to keep in mind. Even so, I'm almost certain this is not the root-cause of the issue; if they somehow did change the way network configuration is derived, we should see it error out beforehand or at least act more erratically.
 
> ...

As for the rest, I'll try to have a look tomorrow. The primary IP changes to the server interface are still somewhat of a mystery to me and behave in unexpected ways (#88 is still open due to this for example). I hope to provide an instrumented build that will output the JSON being passed to the Hetzner API, perhaps we can get clues from that.

**Comment by JonasProgrammer** [comment]
Should work now. I did a little oopsie when refactoring some parts of the network setup to support #88 and passed the server create options to my supposedly-modifying `setPublicNetIfNeeded` by value...

**Comment by makmarius** [comment]
Can confirm! Many thanks, again! 🙇🏼 🚀
