### ISSUE TITLE
metadata.name: Invalid value: "hetzner_instrumentedconfig"

### ISSUE THREAD

**Issue by SasRei** [JonasProgrammer/docker-machine-driver-hetzner#94]
to add more nodes in rancher, i had to update to node-driver 3.10. apparently the name changed to Hetzner_instrumented at some point. now i get the error message:

2023/01/25 09:19:45 [ERROR] error syncing 'nd-qv2sx': handler node-driver-controller: DynamicSchema.management.cattle.io "hetzner_instrumentedconfig" is invalid: metadata.name: Invalid value: "hetzner_instrumentedconfig": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), requeuing

 and i can't edit the node_templates anymore.

Browser Console:
Uncaught (in promise) Error: Property set failed: object in path "config" could not be found.

regards
Sascha

**Comment by JonasProgrammer** [comment]
That's rather strange. I have added an additional binary, `docker-machine-driver-hetzner_instrumented` to the artifacts, but that is just for debugging purposes, when something goes wrong. Normal users should not interact with that.

I have no idea what Rancher does internally, though. Could you check if it works if you re-package the 3.10 release with just the `docker-machine-driver-hetzner` binary and use that as a driver URL (perhaps using `file:///`)?

**Comment by SasRei** [comment]
Hi Jonas,

without the "docker-machine-driver-hetzner_instrumented" binary, everything seems to work. it names the driver correctly and i am able to choose the right template. 

rancher takes the last binary that it finds. I have added a third binary and named it so that it is the last one.

![image](https://user-images.githubusercontent.com/105783894/214783014-17282293-ae74-473a-8f2d-0d2063d16a42.png)

regards
Sascha

**Comment by JonasProgrammer** [comment]
For reference from #94

> 
> > Node Driver's name is changed to "Hetzner_instrumented" to[o], btw.
> 
> Yes and no, the driver name hasn't changed, I have just packaged an additional binary for convenience. Vanilla docker machine users can use `-d hetzner_instrumented` rather than `-d hetzner` to get a driver binary producing much more debug output (potentially leaking confident information -- hence this is not in the normal binary), so I thought it would be helpful to have that built as-is. However, now seeing two issues (#94 and this) about the very same issue, I guess we cannot have nice things and I have to remove that config from the release builds. `Go-releaser` won't let me package them as separate archives either, as they deem two archives per architecture too confusing...

I will take them out with a maintenance update
